# Generated by Django 5.1.1 on 2024-12-10 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='class_teacher',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, null=True)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
