# Generated by Django 5.1.1 on 2024-10-08 14:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=core.models.generate_id, max_length=20, unique=True),
        ),
    ]
