# Generated by Django 5.1.1 on 2024-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='The name must be in the format YYYY-YY (e.g., 2024-25)', max_length=8, unique=True),
        ),
    ]
