# Generated by Django 5.1.1 on 2024-11-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='teacher_id',
            new_name='acc_id',
        ),
    ]
