# Generated by Django 5.1.1 on 2024-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_yourmodel_alter_teacher_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='section',
            field=models.CharField(default=-23, max_length=1),
            preserve_default=False,
        ),
    ]
