# Generated by Django 5.1.1 on 2024-10-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_standard_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='section',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
