# Generated by Django 5.1.1 on 2024-11-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_teacher_id_userprofile_acc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
