# Generated by Django 5.1.1 on 2024-12-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_academicyear_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
