# Generated by Django 5.1.1 on 2024-11-14 07:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_address_line_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=core.models.generate_id, max_length=8, null=True),
        ),
    ]
