# Generated by Django 5.1.1 on 2024-12-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_academicyear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
