# Generated by Django 5.1.1 on 2024-11-14 07:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=core.models.generate_id, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('PE', 'Permanent Employee'), ('CE', 'Contract Employee')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subject_teaching', to='core.subject'),
        ),
    ]
