# Generated by Django 5.1.1 on 2024-10-27 08:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_standard_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default=core.models.generate_sub_code, max_length=10, unique=True),
        ),
    ]
