# Generated by Django 5.1.1 on 2024-11-14 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
