# Generated by Django 5.1.1 on 2024-12-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_class_class_teacher_class_user'),
        ('student', '0018_alter_student_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_monitor_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_boy_of', to='student.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_monitor_girl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_girl_of', to='student.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='core.subject'),
        ),
    ]
