# Generated by Django 5.1.1 on 2024-11-17 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name must be in the format YYYY-YY (e.g., 2024-25)', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_year_format', message='The name must be in the format YYYY-YY (e.g., 2024-25)', regex='^\\d{4}-\\d{2}$')])),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
