# Generated by Django 5.1.1 on 2024-11-17 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_academicyear_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='The name must be in the format YYYY-YY (e.g., 2024-25)', max_length=20, validators=[django.core.validators.RegexValidator(message='The name must be in the format YYYY-YY (e.g., 2024-25)', regex='^\\d{4}-\\d{2}$')]),
        ),
    ]
