# Generated by Django 5.1.1 on 2024-12-25 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicalclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_monitor_boy',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'STU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_boy_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_monitor_girl',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'STU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_girl_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='class_monitor_boy',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'STU'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='class_monitor_girl',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'user_type': 'STU'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
