# Generated by Django 5.1.1 on 2024-11-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_academicyear_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollment_date',
            new_name='create_date',
        ),
    ]
