# Generated by Django 5.1.1 on 2024-12-08 16:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('adhar_number', models.CharField(max_length=12)),
                ('religion', models.CharField(choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('sikhism', 'Sikhism'), ('atheism', 'Atheism'), ('other', 'Other')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('profile_creation_date', models.DateField(auto_now_add=True)),
                ('last_school_name', models.CharField(max_length=255)),
                ('last_class_attended', models.CharField(max_length=100)),
                ('examination_board', models.CharField(max_length=100)),
                ('percentage_or_grade', models.CharField(max_length=50)),
                ('leaving_certificate_date', models.DateField()),
                ('leaving_certificate_number', models.CharField(max_length=100)),
                ('uid_number', models.CharField(max_length=100)),
                ('nationality', models.CharField(choices=[('in', 'India'), ('o', 'Other')], max_length=10)),
                ('residential_address', models.TextField()),
                ('residential_city', models.CharField(max_length=100)),
                ('residential_state', models.CharField(max_length=100)),
                ('residential_pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
                ('permanent_address', models.TextField()),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_state', models.CharField(max_length=100)),
                ('permanent_pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
                ('local_guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('local_guardian_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('local_guardian_address', models.TextField(blank=True, null=True)),
                ('local_guardian_health_problem', models.TextField(blank=True, null=True)),
                ('relation_to_guardian', models.CharField(blank=True, help_text='Relation to the guardian, e.g. Uncle, Aunt', max_length=50, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_age', models.IntegerField()),
                ('father_education', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_organisation', models.CharField(max_length=100)),
                ('father_designation', models.CharField(max_length=100)),
                ('father_languages_known', models.CharField(max_length=200)),
                ('father_mobile_number', models.CharField(max_length=15)),
                ('father_email', models.EmailField(max_length=254)),
                ('father_phone', models.CharField(max_length=20)),
                ('father_annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_age', models.IntegerField()),
                ('mother_education', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_organisation', models.CharField(max_length=100)),
                ('mother_designation', models.CharField(max_length=100)),
                ('mother_languages_known', models.CharField(max_length=200)),
                ('mother_mobile_number', models.CharField(max_length=15)),
                ('mother_email', models.EmailField(max_length=254)),
                ('mother_phone', models.CharField(max_length=20)),
                ('mother_annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('cancel_enroll', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
