# Generated by Django 5.1.1 on 2024-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_enrollment_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
