# Generated by Django 5.1.1 on 2024-12-11 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_father_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adhar_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$')]),
        ),
    ]
