# Generated by Django 5.1.1 on 2024-12-11 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_adhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adhar_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='Aadhar number must be exactly 12 digits.')], verbose_name='Aadhar Number'),
        ),
    ]
