# Generated by Django 5.1.1 on 2024-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uid_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='leaving_certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a passport size photo of the student', null=True, upload_to='student_photos/', verbose_name='Student Photo'),
        ),
    ]
