# Generated by Django 5.1.1 on 2024-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_student_uid_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a valid image file (JPG, PNG, etc.) not exceeding 500 KB.', null=True, upload_to='student_photos/', verbose_name='Student Photo'),
        ),
    ]
