# Generated by Django 5.1.1 on 2024-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_mother_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
