# Generated by Django 5.1.1 on 2024-12-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_father_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student',)},
        ),
    ]
