# Generated by Django 5.1.1 on 2024-12-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_class_total_students'),
        ('student', '0016_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
