# Generated by Django 5.1.1 on 2024-12-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='residential_address',
            field=models.TextField(max_length=70),
        ),
    ]
