# Generated by Django 5.1.1 on 2024-11-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('present_boy', models.PositiveIntegerField(default=0, editable=False)),
                ('present_girl', models.PositiveIntegerField(default=0, editable=False)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_standard', to='core.standard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_teacher', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MarkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('standard', 'datetime'), name='unique_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='markattendance',
            constraint=models.UniqueConstraint(fields=('attendance', 'student'), name='unique_student_per_attendance'),
        ),
    ]
