# Generated by Django 5.1.1 on 2024-11-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.PositiveIntegerField()),
                ('paid_fees', models.PositiveIntegerField(default=0)),
                ('remaining_fees', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_collection', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(auto_created=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fees_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='fees.feescollection')),
            ],
        ),
    ]
