# Generated by Django 5.1.1 on 2024-11-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_is_active'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_collection', to='core.student'),
        ),
    ]
