# Generated by Django 5.1.1 on 2024-11-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feescollection_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feescollection',
            name='academic_year',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
