# Generated by Django 5.1.1 on 2024-11-17 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_enrollment_cancel_enroll'),
        ('fees', '0003_feescollection_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feescollection',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='feescollection',
            name='student',
        ),
        migrations.AddField(
            model_name='feescollection',
            name='enrollment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fees_collections', to='enrollment.enrollment'),
            preserve_default=False,
        ),
    ]
