# Generated by Django 5.1.1 on 2024-12-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_webpushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('M', 'Management Admin'), ('STA', 'Staff'), ('P', 'Principal'), ('T', 'Teacher'), ('STU', 'Student')], max_length=20),
        ),
    ]
