# Generated by Django 5.1.1 on 2024-12-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
