# Generated by Django 5.1.1 on 2024-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_phone_number_profile_contact_number_and_more'),
        ('core', '0008_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='core.subject'),
        ),
    ]
