# Generated by Django 5.1.1 on 2024-12-22 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_historicalprofile_state_alter_profile_state'),
        ('core', '0008_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='certificate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='field_of_study',
            field=models.CharField(default=0, max_length=50, verbose_name='Field of Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='whatsapp_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='year_of_experience',
            field=models.CharField(default=0, max_length=12, verbose_name='Years of Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(default='', max_length=50, verbose_name='Field of Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='year_of_experience',
            field=models.CharField(default=0, max_length=12, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='achivements',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Achivements or Certifications'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='employment_type',
            field=models.CharField(choices=[('PE', 'Permanent Employee'), ('CE', 'Contract Employee')], max_length=2, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='specializations',
            field=models.CharField(blank=True, max_length=50, verbose_name='Specializ In'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='achivements',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Achivements or Certifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_type',
            field=models.CharField(choices=[('PE', 'Permanent Employee'), ('CE', 'Contract Employee')], max_length=2, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.CharField(blank=True, max_length=50, verbose_name='Specializ In'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='core.subject', verbose_name='Subject Taught'),
        ),
    ]
