# Generated by Django 5.1.1 on 2024-12-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_historicalprofile_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='experience',
            field=models.CharField(help_text='As a Teacher or in any other field', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(help_text='As a Teacher or in any other field', max_length=50),
        ),
    ]
