# Generated by Django 5.1.1 on 2024-12-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_historicalprofile_achivements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='experience',
            field=models.CharField(blank=True, help_text='As a Teacher or in any other field', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='photo',
            field=models.TextField(blank=True, help_text='Upload a valid image file (JPG, PNG, etc.) not exceeding 500 KB.', max_length=100, null=True, verbose_name='User Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, help_text='As a Teacher or in any other field', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a valid image file (JPG, PNG, etc.) not exceeding 500 KB.', null=True, upload_to='user_profile_photos/', verbose_name='User Photo'),
        ),
    ]
