# Generated by Django 5.1.1 on 2024-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='paid_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feescollection',
            name='payment_status',
            field=models.CharField(choices=[('complete_paid', 'Complete Paid'), ('partially_paid', 'Partially Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='feescollection',
            name='remaning_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='paid_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='payment_status',
            field=models.CharField(choices=[('complete_paid', 'Complete Paid'), ('partially_paid', 'Partially Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='remaning_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
