# Generated by Django 5.1.1 on 2024-12-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0003_alter_feescollection_enrollment'),
        ('student', '0011_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_collection', to='student.enrollment'),
        ),
    ]
