# Generated by Django 5.1.1 on 2024-12-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0004_alter_feescollection_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='fees_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_collection', to='school_fees.feesstructure'),
        ),
    ]
