# Generated by Django 5.1.1 on 2024-12-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0005_alter_feescollection_fees_structure'),
        ('student', '0011_alter_student_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feescollection',
            unique_together={('enrollment',)},
        ),
    ]
