# Generated by Django 5.1.1 on 2024-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0006_alter_feescollection_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feescollection',
            name='school_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feescollection',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalfeescollection',
            name='school_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalfeescollection',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
