# Generated by Django 5.1.1 on 2024-12-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0009_feescollection_final_school_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feescollection',
            old_name='final_school_fee',
            new_name='paid_school_fee',
        ),
        migrations.RenameField(
            model_name='feescollection',
            old_name='final_transport_fee',
            new_name='paid_transport_fee',
        ),
        migrations.RenameField(
            model_name='historicalfeescollection',
            old_name='final_school_fee',
            new_name='paid_school_fee',
        ),
        migrations.RenameField(
            model_name='historicalfeescollection',
            old_name='final_transport_fee',
            new_name='paid_transport_fee',
        ),
    ]
