# Generated by Django 5.1.1 on 2024-12-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0010_rename_final_school_fee_feescollection_paid_school_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feescollection',
            old_name='paid_fees',
            new_name='total_paid_fees',
        ),
        migrations.RenameField(
            model_name='historicalfeescollection',
            old_name='paid_fees',
            new_name='total_paid_fees',
        ),
    ]
