# Generated by Django 5.1.1 on 2024-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0011_rename_paid_fees_feescollection_total_paid_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feescollection',
            name='total_paid_fees',
        ),
        migrations.RemoveField(
            model_name='historicalfeescollection',
            name='total_paid_fees',
        ),
        migrations.AlterField(
            model_name='feescollection',
            name='paid_school_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feescollection',
            name='paid_transport_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feescollection',
            name='remaning_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feescollection',
            name='school_fee_concession',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feescollection',
            name='transport_fee_concession',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='paid_school_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='paid_transport_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='remaning_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='school_fee_concession',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalfeescollection',
            name='transport_fee_concession',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
