# Generated by Django 5.1.1 on 2024-12-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0012_remove_feescollection_total_paid_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feescollection',
            name='total_paid_fees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalfeescollection',
            name='total_paid_fees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
