# Generated by Django 5.1.1 on 2024-12-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0014_historicalinvoince_invoince'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoince',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='invoince',
            name='total_fee',
        ),
    ]
