# Generated by Django 5.1.1 on 2024-12-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0015_remove_historicalinvoince_total_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoince',
            name='school_fee',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='historicalinvoince',
            name='transport_fee',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='invoince',
            name='school_fee',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='invoince',
            name='transport_fee',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
