# Generated by Django 5.1.1 on 2024-12-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0016_alter_historicalinvoince_school_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoince',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoince',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalinvoince',
            name='school_fee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalinvoince',
            name='transport_fee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoince',
            name='school_fee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoince',
            name='transport_fee',
            field=models.PositiveIntegerField(),
        ),
    ]
