# Generated by Django 5.1.1 on 2024-12-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0017_historicalinvoince_canceled_invoince_canceled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinvoince',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Invoice', 'verbose_name_plural': 'historical Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoince',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
    ]
