# Generated by Django 5.1.1 on 2024-12-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0018_alter_historicalinvoince_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoince',
            name='invoice_number',
            field=models.CharField(db_index=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoince',
            name='invoice_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
