# Generated by Django 5.1.1 on 2024-12-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0019_historicalinvoince_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinvoince',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical invoince', 'verbose_name_plural': 'historical invoinces'},
        ),
        migrations.AlterModelOptions(
            name='invoince',
            options={},
        ),
    ]
