# Generated by Django 5.1.1 on 2024-12-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0021_alter_historicalinvoince_transport_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoince',
            name='transport_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoince',
            name='transport_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
