# Generated by Django 5.1.1 on 2024-12-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0022_alter_historicalinvoince_transport_fee_and_more'),
        ('student', '0016_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_collection', to='student.enrollment'),
        ),
    ]
