# Generated by Django 5.1.1 on 2024-12-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0023_alter_feescollection_enrollment'),
        ('student', '0016_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_collection', to='student.enrollment'),
        ),
    ]
