# Generated by Django 5.1.1 on 2024-12-16 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0024_alter_feescollection_enrollment'),
        ('student', '0017_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_collection', to='student.enrollment'),
        ),
    ]
