# Generated by Django 5.1.1 on 2024-12-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0025_alter_feescollection_enrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feescollection',
            unique_together=set(),
        ),
    ]
