# Generated by Django 5.1.1 on 2024-12-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_class_total_students'),
        ('school_fees', '0026_alter_feescollection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='class_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fees_structure', to='core.class'),
            preserve_default=False,
        ),
    ]
