# Generated by Django 5.1.1 on 2024-12-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_class_total_students'),
        ('school_fees', '0027_alter_feesstructure_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_structure', to='core.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='school_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='School Fee'),
        ),
        migrations.AlterField(
            model_name='historicalfeesstructure',
            name='class_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='historicalfeesstructure',
            name='school_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='School Fee'),
        ),
    ]
