# Generated by Django 5.1.1 on 2024-12-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0028_alter_feesstructure_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescollection',
            name='fees_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees_collection', to='school_fees.feesstructure'),
        ),
    ]
