# Generated by Django 5.1.1 on 2024-12-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0029_alter_feescollection_fees_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransportfees',
            name='bus_route',
            field=models.CharField(max_length=100, verbose_name='Bus Route'),
        ),
        migrations.AlterField(
            model_name='historicaltransportfees',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fare'),
        ),
        migrations.AlterField(
            model_name='transportfees',
            name='bus_route',
            field=models.CharField(max_length=100, verbose_name='Bus Route'),
        ),
        migrations.AlterField(
            model_name='transportfees',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fare'),
        ),
    ]
