# Generated by Django 5.1.1 on 2024-12-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0030_alter_historicaltransportfees_bus_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoince',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoince',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
