# Generated by Django 5.1.1 on 2024-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_exams_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexams',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
