# Generated by Django 5.1.1 on 2024-12-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_exams_exam_alter_historicalexams_exam'),
        ('core', '0008_alter_class_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together={('exam', 'class_name', 'academic_year')},
        ),
    ]
