# Generated by Django 5.1.1 on 2024-12-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_historicalteachertest_historicaltimetable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteachertest',
            name='total_marks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teachertest',
            name='total_marks',
            field=models.PositiveIntegerField(),
        ),
    ]
