# Generated by Django 5.1.1 on 2024-11-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_academicyear_name'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='standard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.standard'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year', 'standard')},
        ),
    ]
