# Generated by Django 5.1.1 on 2024-11-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_enrollment_date_student_create_date'),
        ('enrollment', '0005_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
