# Generated by Django 5.1.1 on 2024-11-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cancel_enroll',
            field=models.BooleanField(default=True),
        ),
    ]
