# Generated by Django 5.1.1 on 2024-11-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_student_standard'),
        ('enrollment', '0007_enrollment_cancel_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.academicyear'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.standard'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student'),
        ),
    ]
