# Generated by Django 5.1.1 on 2024-11-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_alter_enrollment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='cancel_enroll',
            field=models.BooleanField(default=False),
        ),
    ]
